entreprise:
    resource: "@EntrepriseBundle/Resources/config/routing.yml"
    prefix:   /

hello_word:
    resource: "@HelloWordBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

